# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gb9DBUhZsr8VyNmF6_KQjyNVNDQd0GNO
"""

!pip install ultralytics -q

from google.colab import drive
drive.mount('/content/drive')

!yolo detect predict model=yolov8m.pt source='/content/sim test.mp4'

!ffmpeg -i {"/content/runs/detect/predict2/sim_test.avi"} -vcodec libx264 {"/content/drive/MyDrive/1075/final.mp4"}